version: '3.3'
services:
  enrollments_sqelf:
    container_name: enrollments_sqelf
    image: 'datalust/sqelf:latest'
    depends_on:
      - enrollments_seq
    ports:
      - '12201:12201/udp'
    environment:
      SEQ_ADDRESS: 'http://seq:5341'
    restart: unless-stopped
  enrollments_seq:
    container_name: enrollments_seq
    image: 'datalust/seq:latest'
    ports:
      - '5341:80'
    environment:
      ACCEPT_EULA: 'Y'
    restart: unless-stopped
    volumes:
      - 'seq-data:/data'
volumes:
  seq-data:
    external: false
